/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import cl.pablo.lopezpabloexamenpyg.Equipo;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.ArraysDB;
import model.ReporteODM;

/**
 *
 * @author pablo
 */
public class InformeEquiposVendidos extends javax.swing.JFrame {

    /**
     * Creates new form InformeEquiposVendidos
     */
    ArraysDB DB;

    public InformeEquiposVendidos() {
        initComponents();
        DB = ArraysDB.getConexion();
        List<ReporteODM> listaReporte = DB.ObtenerDatosReporte();
        tbl_equipos_vendidos.setModel(new DefaultTableModel(new String[]{
            "Nombre comprador",
            "Modelo equipo vendido",
            "Telefono cliente",
            "Correo cliente",
            "Precio",}, listaReporte.size()
        ));
        // por cada objeto en la lista se crea una nueva fila con sus datos;

        for (int i = 0; i < listaReporte.size(); i++) {
            tbl_equipos_vendidos.setValueAt(listaReporte.get(i).getNombre(), i, 0);
            tbl_equipos_vendidos.setValueAt(listaReporte.get(i).getModelo(), i, 1);
            tbl_equipos_vendidos.setValueAt(listaReporte.get(i).getTelefono(), i, 2);
            tbl_equipos_vendidos.setValueAt(listaReporte.get(i).getCorreo(), i, 3);
            tbl_equipos_vendidos.setValueAt(listaReporte.get(i).getPrecio(), i, 4);

        }
//        for (int i = 0; i < tbl_equipos_vendidos.getRowCount()-1; i++){
//                tbl_equipos_vendidos.remove(i);
//            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_equipos_vendidos = new javax.swing.JTable();
        btn_volver = new javax.swing.JButton();
        cbx_filtro_tipo_equipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Informe equipos vendidos");

        tbl_equipos_vendidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_equipos_vendidos);

        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });

        cbx_filtro_tipo_equipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Laptop", "Desktop", " " }));
        cbx_filtro_tipo_equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_filtro_tipo_equipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbx_filtro_tipo_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_filtro_tipo_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_volver)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        GenerarReporte generarReporte = new GenerarReporte();
        generarReporte.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_volverActionPerformed

    //ARREGLAR FILTRO: La tabla no se resetea
    private void cbx_filtro_tipo_equipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_filtro_tipo_equipoActionPerformed
        // TODO add your handling code here:
//        if (cbx_filtro_tipo_equipo.getSelectedItem().equals("Todos")) {
//            List<ReporteODM> listaReporte = DB.ObtenerDatosReporte();
//            System.out.println(listaReporte);
//            for (int i = 0; i < tbl_equipos_vendidos.getRowCount(); i++){
//                tbl_equipos_vendidos.remove(i);
//            }
//            for (int i = 0; i < listaReporte.size(); i++) {
//                tbl_equipos_vendidos.setValueAt(listaReporte.get(i).getNombre(), i, 0);
//                tbl_equipos_vendidos.setValueAt(listaReporte.get(i).getModelo(), i, 1);
//                tbl_equipos_vendidos.setValueAt(listaReporte.get(i).getTelefono(), i, 2);
//                tbl_equipos_vendidos.setValueAt(listaReporte.get(i).getCorreo(), i, 3);
//                tbl_equipos_vendidos.setValueAt(listaReporte.get(i).getPrecio(), i, 4);
//            }
//        } else if (cbx_filtro_tipo_equipo.getSelectedItem().equals("Laptop")) {
//            List<ReporteODM> listaReporte = DB.ObtenerDatosReporteFiltrado("Laptop");
//            System.out.println(listaReporte);
//            for (int i = 0; i < tbl_equipos_vendidos.getRowCount(); i++){
//                tbl_equipos_vendidos.remove(i);
//            }
//            for (int i = 0; i < listaReporte.size(); i++) {
//                tbl_equipos_vendidos.setValueAt(listaReporte.get(i).getNombre(), i, 0);
//                tbl_equipos_vendidos.setValueAt(listaReporte.get(i).getModelo(), i, 1);
//                tbl_equipos_vendidos.setValueAt(listaReporte.get(i).getTelefono(), i, 2);
//                tbl_equipos_vendidos.setValueAt(listaReporte.get(i).getCorreo(), i, 3);
//                tbl_equipos_vendidos.setValueAt(listaReporte.get(i).getPrecio(), i, 4);
//            }
//        } else if (cbx_filtro_tipo_equipo.getSelectedItem().equals("Desktop")){
//            List<ReporteODM> listaReporte = DB.ObtenerDatosReporteFiltrado("Desktop");
//            System.out.println(listaReporte);
//            for (int i = 0; i < tbl_equipos_vendidos.getRowCount(); i++){
//                tbl_equipos_vendidos.remove(i);
//            }
//            for (int i = 0; i < listaReporte.size(); i++) {
//                tbl_equipos_vendidos.setValueAt(listaReporte.get(i).getNombre(), i, 0);
//                tbl_equipos_vendidos.setValueAt(listaReporte.get(i).getModelo(), i, 1);
//                tbl_equipos_vendidos.setValueAt(listaReporte.get(i).getTelefono(), i, 2);
//                tbl_equipos_vendidos.setValueAt(listaReporte.get(i).getCorreo(), i, 3);
//                tbl_equipos_vendidos.setValueAt(listaReporte.get(i).getPrecio(), i, 4);
//            }
//        }
    }//GEN-LAST:event_cbx_filtro_tipo_equipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformeEquiposVendidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformeEquiposVendidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformeEquiposVendidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformeEquiposVendidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformeEquiposVendidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox<String> cbx_filtro_tipo_equipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_equipos_vendidos;
    // End of variables declaration//GEN-END:variables
}
