/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import cl.pablo.lopezpabloexamenpyg.Cliente;
import cl.pablo.lopezpabloexamenpyg.Desktop;
import cl.pablo.lopezpabloexamenpyg.Equipo;
import cl.pablo.lopezpabloexamenpyg.Laptop;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.ArraysDB;

/**
 *
 * @author pablo
 */
public class ListadoEquipos extends javax.swing.JFrame {

    ArraysDB DB;

    /**
     * Creates new form ListadoEquipos
     */
    public ListadoEquipos() {
        initComponents();
        DB = ArraysDB.getConexion();
        List<Equipo> listEqui = DB.listar_equipos();
        tbl_lista_equipos.setModel(new DefaultTableModel(new String[]{
            "Modelo",
            "CPU",
            "Tamaño disco duro",
            "Tamaño memoria RAM",
            "Precio",
            "Tipo de equipo",}, listEqui.size()
        ));

        for (int i = 0; i < listEqui.size(); i++) {
            String precioString = String.valueOf(listEqui.get(i).getPrecio());
            tbl_lista_equipos.setValueAt(listEqui.get(i).getModelo(), i, 0);
            tbl_lista_equipos.setValueAt(listEqui.get(i).getCpu(), i, 1);
            tbl_lista_equipos.setValueAt(listEqui.get(i).getDiscoDuro(), i, 2);
            tbl_lista_equipos.setValueAt(listEqui.get(i).getRam(), i, 3);
            tbl_lista_equipos.setValueAt(precioString, i, 4);
            tbl_lista_equipos.setValueAt(listEqui.get(i).getTipoEquipo(), i, 5);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_lista_equipos = new javax.swing.JTable();
        btn_volver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbx_filtrarPor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_lista_equipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_lista_equipos);

        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });

        jLabel1.setText("REGISTRO DE EQUIPOS");

        cbx_filtrarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtrar por:", "Desktop", "Laptop", "Todos" }));
        cbx_filtrarPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_filtrarPorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbx_filtrarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbx_filtrarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btn_volver)
                .addGap(38, 38, 38))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        RegistroEquipo registroEquipo = new RegistroEquipo();
        registroEquipo.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_volverActionPerformed

    private void cbx_filtrarPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_filtrarPorActionPerformed
        // TODO add your handling code here:

        if (cbx_filtrarPor.getSelectedItem().equals("Laptop")) {
            List<Laptop> listaLaptop = new ArrayList();
            tbl_lista_equipos.setModel(new DefaultTableModel(new String[]{
                "Modelo",
                "CPU",
                "Tamaño disco duro",
                "Tamaño memoria RAM",
                "Precio",
                "Tipo de equipo",
                "Tamaño de la pantalla",
                "Cantidad de puertos USB",}, listaLaptop.size()
            ));
        } else if (cbx_filtrarPor.getSelectedItem().equals("Desktop")) {
            List<Desktop> listaDesktop = new ArrayList();
            tbl_lista_equipos.setModel(new DefaultTableModel(new String[]{
                "Modelo",
                "CPU",
                "Tamaño disco duro",
                "Tamaño memoria RAM",
                "Precio",
                "Tipo de equipo",
                "Factor forma",
                "Fuente de poder",}, listaDesktop.size()));
        }
    }//GEN-LAST:event_cbx_filtrarPorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListadoEquipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox<String> cbx_filtrarPor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_lista_equipos;
    // End of variables declaration//GEN-END:variables
}
