/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author pablo
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_menu_reg_cli = new javax.swing.JButton();
        btn_menu_reg_equi = new javax.swing.JButton();
        btn_menu_inf = new javax.swing.JButton();
        btn_menu_ven = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_menu_reg_cli.setText("Registrar cliente");
        btn_menu_reg_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_reg_cliActionPerformed(evt);
            }
        });

        btn_menu_reg_equi.setText("Registrar equipo");
        btn_menu_reg_equi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_reg_equiActionPerformed(evt);
            }
        });

        btn_menu_inf.setText("Generar informe");
        btn_menu_inf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_infActionPerformed(evt);
            }
        });

        btn_menu_ven.setText("Iniciar venta");
        btn_menu_ven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_venActionPerformed(evt);
            }
        });

        jLabel1.setText("Escoja la acción que desea realizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btn_menu_inf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(btn_menu_ven)
                .addGap(108, 108, 108))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btn_menu_reg_cli)
                        .addGap(94, 94, 94)
                        .addComponent(btn_menu_reg_equi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_menu_reg_cli)
                    .addComponent(btn_menu_reg_equi))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_menu_inf)
                    .addComponent(btn_menu_ven))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_menu_reg_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_reg_cliActionPerformed
        // TODO add your handling code here:
        RegistroCliente registroCliente = new RegistroCliente();
        registroCliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_menu_reg_cliActionPerformed

    private void btn_menu_reg_equiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_reg_equiActionPerformed
        // TODO add your handling code here:
        RegistroEquipo registroEquipo = new RegistroEquipo();
        registroEquipo.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_menu_reg_equiActionPerformed

    private void btn_menu_infActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_infActionPerformed
        // TODO add your handling code here:
        Informes informe = new Informes();
        informe.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_menu_infActionPerformed

    private void btn_menu_venActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_venActionPerformed
        // TODO add your handling code here:
        IniciarVenta iniciarVenta = new IniciarVenta();
        iniciarVenta.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_menu_venActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_menu_inf;
    private javax.swing.JButton btn_menu_reg_cli;
    private javax.swing.JButton btn_menu_reg_equi;
    private javax.swing.JButton btn_menu_ven;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
